### ISSUE TITLE
Hide prefixes

### ISSUE THREAD

**Issue by Glaconius** [lukasbach/obsidian-file-order#14]
Great job.

Would it be possible to add an option to hide the prefixes so to keep the interface tidy?

Thanks!

**Comment by captureMebutProbablyNot** [comment]
This is what I came for too!

**Comment by lukasbach** [comment]
Hey, good suggestion, but first of all, the rendering logic of the sidebare tree isn't exactly easily exposed in the Obsidian API in a way that it could be changed, and also I'd like to keep render logic out of the scope of this plugin, as it currently just revolves around automating the naming aspect.
