### ISSUE TITLE
Support for top level folders

### ISSUE THREAD

**Issue by houcheng** [lukasbach/obsidian-file-order#16]
@lukasbach,

Maybe it's my missing but I tried for a while but still can not find a way to sort the folders at top level.
I've also tried to enable the "show root folder" in the file tree alternative plugin, but the right-click-menu of 
top level folder only has a "create new folder" feature.

It's seems that the file-order plugin need a button to popup the file sort on top folder? 

Thank you for contribution,
Best regards,
Houcheng

**Comment by lukasbach** [comment]
You can right-click on a non-folder item in the root folder and reorder from that context menu, or use the "Reorder items in top folder" global command.
