### ISSUE TITLE
Ignore folder notes

### ISSUE THREAD

**Issue by alihayeri** [lukasbach/obsidian-file-order#17]
### Obsidian Folder Notes

Hi. I use [obsidian-folder-notes plugin](https://github.com/LostPaul/obsidian-folder-notes) which allows you to create a note for each folder inside it. 

For example, if I have a folder named programming, obsidian-folder-notes can create a note named programming.md inside the programming folder. Note that the name of the note is exactly as the same as the name of the folder (plus .md extension). You can use it this note for many purposes. Let's call these notes "folder notes". A "folder notes" is hidden and can be access by clicking at the folder itself.

I found this plugin useful and I use it. For example, imagine you have some folders inside the programming folder, named Java and Python. You can list and link programming "folder note" to Java and Python "folder notes".

### What is the feature that I'm requesting?

I think it would be wonderful if there was an option that by using it, obsidian-file-order plugin ignores all the folder notes. 

### Questions

**Is your feature request related to a problem? Please describe.**
No. What I'm explaining is not related to a problem.

**Describe the solution you'd like**
An option that we can set it in obsidian-file-order plugin to ingore "folder notes."

**Describe alternatives you've considered**
Unfortunately, I don't know how to write RegEx. I described my desire to ChatGPT, and copied and pasted the RegEx it provided inside the "ignore pattern". But it didn't work. If my request can be done by just using correct RegEx, I would be thankful if someone can help me to write a proper RegEx. The RegEx-s that ChatGPT created for me were: 
"^([^\/]+)\/\1\.txt$"
"^([^/]+)\1\.txt$"

**Additional context**
I don't have any more context to share. But if anymore information is needed, please let me know.

**Comment by lukasbach** [comment]
Hi, thanks for your suggestion. Yeah, Regex won't work in your case since with regex you need to define a pattern for the file name, but there is no way to make that dependent on the folder name.

In version 0.10.0, I've added a new setting "Ignore folder file", if you update and enable the setting, you should get the behavior you are describing.

**Comment by alihayeri** [comment]
Thanks for your reply. You are absolutely right. It was already implemented, I just didn't have the latest verision. I appreciate your help.
