### ISSUE TITLE
Ignore a directory

### ISSUE THREAD

**Issue by Fastidious** [lukasbach/obsidian-file-order#3]
I have Obsidian configured to save media files under an `assets` directory, that is relative to the directory where notes are stored. That means I can have many `assets` directories at many multiple levels, depending on whether or not I have media files on notes. 

How can I configure the plugin to ignore **all** `assets` directories, regardless of where they are? Thanks!

**Comment by Drakemoor** [comment]
In general, it would be good if we could exclude files or folders from the sorting. Many plugins depend on files with specific names. For example, Longform uses an 'index' file in the project directory, which cant be renamed, or Folder Note...
Thank you for the great plugin.
