### ISSUE TITLE
Unable to reorder 1st-level folders

### ISSUE THREAD

**Issue by wuningjing-nm2207** [lukasbach/obsidian-file-order#9]
Unable to reorder folders when right-clicking on 1st-level folders.
![image](https://github.com/lukasbach/obsidian-file-order/assets/125365386/3f591b0d-1e48-4d2f-b7a3-4dec4ef7467d)

Only able to reorder 1st-level folders when right-clicking on 1st-level files.
![image](https://github.com/lukasbach/obsidian-file-order/assets/125365386/850c69a9-9ed1-47d4-8c91-7e627de18966)

If I do not have any 1st level .md files, ie. all my files are within folders, there would be no way to reorder the folders in the first level. Right now I just keep an empty file in the first level and reorder the rest of my folders by right-clicking that file. It works but took a while to figure out this work around.

**Comment by lukasbach** [comment]
Hey, yes great suggestion! I added a new global command "Reorder items in top folder" in v0.0.8 for that use case.
